FROM debian:buster

RUN apt-get update && apt-get -y install \
	wget \
	curl \
	bash \
	php \
	php-cgi \
	php-mysql \
	php-fpm \
	php-pdo \
	php-gd php-cli \
	php-mbstring \
	redis \
	php-redis \
	&& rm -rf /var/lib/apt/lists/*

# Installer WP-CLI afin de gerer wordpress via le terminal du conteneur
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
  && chmod +x wp-cli.phar \
  && mv wp-cli.phar /usr/local/bin/wp

# Copier le fichier de config pour PHP
COPY ./conf/www.conf /etc/php/7.3/fpm/pool.d/

# Necessaire au demarrage de PHP
RUN mkdir /run/php



